Improve readme and add email as example
zenika-open-source/code-moi-un-mouton pull request #30
Opened 2022-04-25 16:09 UTC by MrcdJ

Feedbacks from workshops done with 'CM2' team in March 2022.

2022-04-25 16:13 UTC, victor-gallet commented
LGTM

2022-04-25 19:05 UTC, louiznk requested changes
Un grand merci, c'est un bon compléments. Il y a des ajustements à faire sur le style, j'ai fait quelques suggestions en ce sens

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/README.md
> +Il peut être aussi réalisé par les intervenants Zenika. Cela fait un atelier supplémentaire à animer mais c’est un bon moyen pour faire connaissance avec les élèves et se familiariser avec les classe
```suggestion
Il peut être aussi réalisé par les intervenants externe. Cela fait un atelier supplémentaire à animer mais c’est un bon moyen pour faire connaissance avec les élèves et se familiariser avec les classes, sans se lancer directement sur les PC. On peut aussi profiter de cet atelier supplémentaire pour vérifier, une fois l’atelier terminé, la configuration des PC et installer si besoin Scratch et Thymio.
```
(c'est ouvert à toutes et tous)

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Cet atelier peut aussi être animé par les intervenants Zenika. Cela permet de faire connaissance avec les élèves et de se familiariser avec les classes.
```suggestion
Cet atelier peut aussi être animé par les intervenants. Cela permet de faire connaissance avec les élèves et de se familiariser avec les classes.
```
idem

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Nous allons principalement travailler avec ce bouquin : L’informatique sans ordinateur (pdf que vous pouvez télécharger).
```suggestion
Nous allons principalement travailler avec ce livre : L’informatique sans ordinateur (pdf que vous pouvez télécharger).
 ```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +🤖 **Atelier Thymio sur ordinateur et avec le robot** → Il faut installer le logiciel, vous pouvez suivre les instructions suivantes ou directement solliciter l'informaticien de l'école pour vous le f
Peut être ajouter une note pour windows (quelque chose qui pointe sur https://www.thymio.org/download-thymio-suite-redirect/)

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +😸 **Atelier Scratch sur ordinateur** → Pouvez-vous svp vérifier que Scratch est bien disponible et suffisamment fluide sur vos ordinateurs de classe : https://scratch.mit.edu/ ?
```suggestion
😸 **Atelier Scratch sur ordinateur** → Pouvez-vous svp vérifier que Scratch est bien disponible et fonctionne correctement sur vos ordinateurs de classe : https://scratch.mit.edu/ ?
```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Donc suivre ce lien, tester un rapidement l'interface en allant dans l'onglet "Créer", puis vous amusez avec (il y a une petite vidéo explicative qui apparait). On vous demande juste de voir si le si
```suggestion
En suivant ce lien vous allez pouvoir tester un rapidement l'interface en allant dans l'onglet "Créer", puis vous amusez avec (il y a une petite vidéo explicative qui apparaît). Nous vous vous demandons juste de voir si le site répond normalement ou si vous trouvez que les clics de la souris sont très (trop) lents. Si c'est trop compliqué, sollicitez l'information quand il viendra pour l'installation de Thymio.
```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +
```suggestion
**Les noms, le nombre d'intervenants et le nombre d'élève sont donnés à titre d'exemple**
```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +
```suggestion
**Les noms, le nombre d'intervenants et le nombre d'élève sont donnés à titre d'exemple**
```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- 2 organisations possibles qu'on vous laisse choisir :
```suggestion
- 2 organisations possibles que nous vous laissons choisir :
```

2022-04-25 19:05 UTC, louiznk commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et comme il n'y a pas assez de robots pour tous (6 c'est déjà super !! et merci pour cela !). Donc si vous choisissez l'o
```suggestion
- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et il n'y a pas assez de robots pour tous. Si vous choisissez l'organisation 1, nous vous laissons gérer la constitution des groupes entre ceux qui veulent continuer de découvrir Thymio et ceux qui préfèrent Scratch.
```

2022-04-26 06:33 UTC, P0ppoff requested changes

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Dans la classe, avec tous les élèves, lors de la 1e rencontre.
```suggestion
Dans la classe, avec tous les élèves, lors de la 1ère rencontre.
```

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +\# 1. Chaque intervenant se présente. Des idées pour se présenter :
Par soucis d'uniformité, il y a pas d'espaces dans les parties en dessous `\#1`

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +- Distribuer à chacun une planche avec des images d’objets [insérer planche objets]
Il te manque le lien de la `planche objets` ?

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +- Debriefer tous ensemble.
```suggestion
- Débriefer tous ensemble.
```

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Définir un zonage dans la salle de classe pour délimiter l’espace pouvant être emprunté. Il est plus facile d'être dans un espace ouvert comme la cours d'école ou gymnase et d'utiliser des plots, cer
```suggestion
Définir un zonage dans la salle de classe pour délimiter l’espace pouvant être emprunté. Il est plus facile d'être dans un espace ouvert comme la cour d'école ou gymnase et d'utiliser des plots, cerceaux, craies pour dessiner sur le sol.
```
https://leconjugueur.lefigaro.fr/blog/quand-ecrire-cour-cours-court-et-courre/

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +👨 Martin (architecte logiciel).
Pourquoi il a un point lui `.` ? Il est spécial *Martin* ?

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +## ------ 🚧 PREPARATION CÔTÉ INSTIT 🚧 ------
```suggestion
## ------ 🚧 PRÉPARATION CÔTÉ INSTIT 🚧 ------
```

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Donc suivre ce lien, tester un rapidement l'interface en allant dans l'onglet "Créer", puis vous amusez avec (il y a une petite vidéo explicative qui apparait). On vous demande juste de voir si le si
```suggestion
Donc suivre ce lien, tester un peu rapidement l'interface en allant dans l'onglet "Créer", puis vous amusez avec (il y a une petite vidéo explicative qui apparait). On vous demande juste de voir si le site répond normalement ou si vous trouvez que les clics de la souris sont très (trop) lents. Si un peu galère pour vous, sollicitez l'information quand il viendra pour l'installation de Thymio.
```

Le reste de la phrase n'est pas cohérent je trouve.

2022-04-26 06:33 UTC, P0ppoff commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et comme il n'y a pas assez de robots pour tous (6 c'est déjà super !! et merci pour cela !). Donc si vous choisissez l'o
```suggestion
- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et il n'y a pas assez de robots pour tous (6 c'est déjà super !! et merci pour cela !). Donc si vous choisissez l'organisation 1, on vous laisse gérer la constitution des groupes entre ceux qui veulent continuer de découvrir Thymio et ceux qui préfèrent Scratch.
```

2022-05-06 13:31 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +- Debriefer tous ensemble.
done

2022-05-06 13:32 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Définir un zonage dans la salle de classe pour délimiter l’espace pouvant être emprunté. Il est plus facile d'être dans un espace ouvert comme la cours d'école ou gymnase et d'utiliser des plots, cer
done
merci pour le conjugueur mais je savais :P j'ai juste écris vite.

2022-05-06 13:32 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +👨 Martin (architecte logiciel).
done

2022-05-06 13:32 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +## ------ 🚧 PREPARATION CÔTÉ INSTIT 🚧 ------
done

2022-05-06 13:32 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et comme il n'y a pas assez de robots pour tous (6 c'est déjà super !! et merci pour cela !). Donc si vous choisissez l'o
done

2022-05-06 13:33 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +- Distribuer à chacun une planche avec des images d’objets [insérer planche objets]
oui ! c'est martin qui l'a sur son ordi... ! Donc j'attends son retour

2022-05-06 13:34 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +\# 1. Chaque intervenant se présente. Des idées pour se présenter :
done

2022-05-06 13:45 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Dans la classe, avec tous les élèves, lors de la 1e rencontre.
right

2022-05-06 13:46 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Dans la classe, avec tous les élèves, lors de la 1e rencontre.
c'est même 1re
[https://www.laculturegenerale.com/1re-1ere-1ere-abreviation-premiere/](url)

2022-05-06 13:48 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- 2 organisations possibles qu'on vous laisse choisir :
done

2022-05-06 13:48 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +- **Pourquoi 2 organisations ?** L'atelier Thymio se fait en binôme par robot et comme il n'y a pas assez de robots pour tous (6 c'est déjà super !! et merci pour cela !). Donc si vous choisissez l'o
done

2022-05-06 13:49 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +
right

2022-05-06 13:49 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +
right

2022-05-06 13:51 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Donc suivre ce lien, tester un rapidement l'interface en allant dans l'onglet "Créer", puis vous amusez avec (il y a une petite vidéo explicative qui apparait). On vous demande juste de voir si le si
done

2022-05-06 13:51 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +😸 **Atelier Scratch sur ordinateur** → Pouvez-vous svp vérifier que Scratch est bien disponible et suffisamment fluide sur vos ordinateurs de classe : https://scratch.mit.edu/ ?
done

2022-05-06 13:59 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Nous allons principalement travailler avec ce bouquin : L’informatique sans ordinateur (pdf que vous pouvez télécharger).
done

2022-05-06 13:59 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +🤖 **Atelier Thymio sur ordinateur et avec le robot** → Il faut installer le logiciel, vous pouvez suivre les instructions suivantes ou directement solliciter l'informaticien de l'école pour vous le f
Done
But error 500 => can't check the link

2022-05-06 14:00 UTC, MrcdJ commented on kit-de-demarrage/emails/email_presentation_ateliers.md
> +Nous allons principalement travailler avec ce bouquin : L’informatique sans ordinateur (pdf que vous pouvez télécharger).
done

2022-05-06 14:00 UTC, MrcdJ commented on kit-de-demarrage/ateliers/atelier_pre-requis.md
> +Cet atelier peut aussi être animé par les intervenants Zenika. Cela permet de faire connaissance avec les élèves et de se familiariser avec les classes.
done

2022-05-06 14:14 UTC, MrcdJ commented on kit-de-demarrage/README.md
> +Il peut être aussi réalisé par les intervenants Zenika. Cela fait un atelier supplémentaire à animer mais c’est un bon moyen pour faire connaissance avec les élèves et se familiariser avec les classe
done

2022-05-06 14:15 UTC, MrcdJ commented on kit-de-demarrage/README.md
> +Il peut être aussi réalisé par les intervenants Zenika. Cela fait un atelier supplémentaire à animer mais c’est un bon moyen pour faire connaissance avec les élèves et se familiariser avec les classe
i didn't know ;)

2022-05-06 16:06 UTC, louiznk approved these changes
:heart:

2022-05-06 18:23 UTC, P0ppoff approved these changes

2022-05-06 18:23 UTC, merged